# Uncomment this to see what gets sourced on initialization
# setopt SOURCE_TRACE
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]];
  then source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# My ssh certs
if [ -f "$HOME/.ssh/.identites" ];
  then source "$HOME/.ssh/.identites";
fi

# My aliases and vars
export GITHUB_USER="amadeus"
alias myssh='ssh amadeus@104.236.168.198'
alias rmpyc='find . -name "*.pyc" -exec rm -rf {} \;'
alias pp='pnpx pierre@latest'

# Prevent esc from delaying in vim
# (used in conjunction with some other settings in vim as well)
export KEYTIMEOUT=1

# Use the vi navigation keys in menu completion
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

if [ -f "$HOME/.localrc" ];
  then source "$HOME/.localrc";
fi
