# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]];
  then source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/.google-cloud-sdk/google-cloud-sdk/path.zsh.inc" ];
  then source "$HOME/.google-cloud-sdk/google-cloud-sdk/path.zsh.inc";
fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/.google-cloud-sdk/google-cloud-sdk/completion.zsh.inc" ];
  then source "$HOME/.google-cloud-sdk/google-cloud-sdk/completion.zsh.inc";
fi

# My ssh certs
if [ -f "$HOME/.ssh/.identites" ];
  then source "$HOME/.ssh/.identites";
fi

# NVM Config
export NVM_DIR="$HOME/.nvm"
if [ -f "$NVM_DIR/nvm.sh" ];
  then source "$NVM_DIR/nvm.sh";
fi

# My aliases and vars
export ARCHFLAGS="-arch x86_64"
export GITHUB_USER="amadeus"
alias myssh='ssh amadeus@104.236.168.198'
alias eightbit='ssh eightbit@184.106.207.72'
alias rmpyc='find . -name "*.pyc" -exec rm -rf {} \;'

# Prevent esc from delaying
KEYTIMEOUT=1

# Use the vi navigation keys in menu completion
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
